---
title: Ext. Fig5b
subtitle:  "Principal component analysis (PCA) of RNA-SEQ data comparing top 500 most variable genes between naive (N; grey) and TCRTAG differentiating during acute infection (green) and in tumors (blue) at 6, 12, 24h post-transfer."
author: "pz"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    highlight: tango
    df_print: paged
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 3
    code_folding: hide
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, result='hold',fig.width=10,tidy=TRUE, cache=FALSE)
knitr::opts_knit$set(progress=TRUE,verbose=TRUE)
```

```{r libraries, cache=FALSE}
library(data.table)
library(magrittr)
library(knitr)
library(ggplot2); theme_set(theme_bw(base_size = 16))
library(DESeq2)
library(dplyr)
```



```{r decoder}
decoderFile <- "decoder.txt"
decoder.data <- fread(decoderFile) %>% as.data.frame()
decoder.data$group <- factor(decoder.data$group, levels = c("N", "E6", "E12", "E24", "L6", "L12", "L24"))
decoder.data$type <- factor(decoder.data$type, levels = c("naive", "effector", "tumor"))
decoder.data$time <- factor(decoder.data$time, levels = c("0hr", "6hr", "12hr", "24hr"))
decoder.data$replicate <- factor(decoder.data$replicate)
decoder.data = decoder.data[order(decoder.data$group),]
row.names(decoder.data) = decoder.data$sample.ID
```


```{r counts}
counts <- read.table(file = "gene.counts.txt", header = TRUE, check.names=FALSE, row.names=1)
decoder.data <- decoder.data[decoder.data$sample.ID %in% colnames(counts),]

if (!identical(colnames(counts), decoder.data$sample.ID)) {
  stop("Column names in counts do not match sample IDs in decoder data")
}

counts <- counts[,c(decoder.data$sample.ID)]
```

# Samples

The following samples were part of this analysis:

```{r samples}
as_tibble(decoder.data)
```

# PCA

```{r createDDS}
dds <- DESeq2::DESeqDataSetFromMatrix(countData = counts, 
                                      colData = decoder.data, 
                                      design = ~ group)

keep <- edgeR::filterByExpr(counts(dds), design = model.matrix(~ group, data = colData(dds)))
dds <- dds[keep,]

dds <- estimateSizeFactors(dds)
vsd <- DESeq2::vst(dds, blind = TRUE)
```

Top 500 most variable genes based on VST normalized data

```{r pca}
ntop = 500
Pvars <- rowVars(assay(vsd))
select <- order(Pvars, decreasing = TRUE)[seq_len(min(ntop, length(Pvars)))]
PCA <- prcomp(t(assay(vsd)[select, ]), scale = F)
percentVar <- round(100*PCA$sdev^2/sum(PCA$sdev^2),1)
dataGG = data.frame(PC1 = PCA$x[,1], PC2 = PCA$x[,2], sampleName = row.names(colData(vsd)),colData(vsd))


ggplot(dataGG, aes(PC1, PC2)) + 
  geom_point(size = 5, aes(color = group), show.legend = T) + 
  theme_bw(base_size = 18) +
  xlab(paste0("PC1: ", round(percentVar[1], 4), "% variance")) + 
  ylab(paste0("PC2: ", round(percentVar[2], 4), "% variance")) + 
  theme(legend.position = "right")   + 
  geom_point(shape = 1, size = 5, colour = "black") + 
  scale_color_manual(values = c("N" = "#636363",
                                "E6" = "#ccece6", 
                                "E12" = "#99d8c9", 
                                "E24" = "#66c2a4", 
                                "L6" = "#c6dbef", 
                                "L12" = "#6baed6",  
                                "L24" = "#4398cb"), name = "") + 
  theme(plot.background = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank())
```



# Session Info
```{r session, message=FALSE, warning=FALSE, cache=FALSE,echo=FALSE, fig.width=10, fig.height=5.5, context="data"}
sessionInfo()
```