---
title: Fig5
subtitle:  "Principal component analysis (PCA) of ATAC-SEQ data."
author: "pz"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    highlight: tango
    df_print: paged
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 3
    code_folding: hide
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, result='hold',fig.width=10,tidy=TRUE, cache=FALSE)
knitr::opts_knit$set(progress=TRUE,verbose=TRUE)
```

```{r libraries, cache=FALSE}
library(data.table)
library(magrittr)
library(knitr)
library(ggplot2); theme_set(theme_bw(base_size = 16))
library(DESeq2)
library(dplyr)
```



```{r decoder}
decoderFile <- "atac_decoder.csv"
decoder.data <- read.table(decoderFile,header=T,stringsAsFactors=F, sep=",")
decoder.data$SampleID = make.names(decoder.data$SampleID)
decoder.data$Condition = factor(decoder.data$Condition)
decoder.data$Condition <- relevel(decoder.data$Condition, ref = "N")
# select early timepoints only
decoder.data = subset(decoder.data, !(Condition %in% c("P10d", "P1d", "P5d")))
decoder.data = subset(decoder.data, (Condition %in% c("N", "E6hr", "E12hr", "E24hr", "L6hr", "L12hr", "L1d")))
decoder.data = subset(decoder.data, batch != "m2017")
```


```{r loadDESeq2Object}
# see runDiffBind.R, runSVA.R
load("sva_dds_vsd.RData")
vsd = vsd[,decoder.data$SampleID]
```

# Samples

The following samples were part of this analysis:

```{r samples}
as_tibble(decoder.data)
```

# PCA


Using the top 25K most variable peaks,based on VST normalized data

```{r pca}
ntop = 25000
Pvars <- rowVars(assay(vsd))
select <- order(Pvars, decreasing = TRUE)[seq_len(min(ntop, length(Pvars)))]
PCA <- prcomp(t(assay(vsd)[select, ]), scale = F)
percentVar <- round(100*PCA$sdev^2/sum(PCA$sdev^2),1)
dataGG =  merge( data.frame(PC1 = PCA$x[,1], PC2 = PCA$x[,2]), as.data.frame(colData(vsd)), by="row.names")
dataGG$Condition = factor(dataGG$Condition, levels=c("N", "E6hr", "E12hr", "E24hr","L6hr", "L12hr", "L1d"))

ggplot(dataGG, aes(PC1, PC2)) + 
  geom_point(size = 5, aes(color = Condition), show.legend = T) + 
  theme_bw(base_size = 18) +
  xlab(paste0("PC1: ", round(percentVar[1], 4), "% variance")) + 
  ylab(paste0("PC2: ", round(percentVar[2], 4), "% variance")) + 
  theme(legend.position = "right")   + 
  geom_point(shape = 1, size = 5, colour = "black") + 
  scale_color_manual(values = c("N" = "#636363",
                                "E6hr" = "#ccece6", 
                                "E12hr" = "#99d8c9", 
                                "E24hr" = "#66c2a4", 
                                "L6hr" = "#c6dbef", 
                                "L12hr" = "#6baed6",  
                                "L1d" = "#4398cb"), name = "") + 
  theme(plot.background = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank())
```



# Session Info
```{r session, message=FALSE, warning=FALSE, cache=FALSE,echo=FALSE, fig.width=10, fig.height=5.5, context="data"}
sessionInfo()
```