---
title: Fig. 4b
subtitle: "Principal component analysis (PCA) comparing peak accessibility of naïve (N; grey) TCRTAG differentiating during acute infection (green series) and in tumors (blue series) at 6h, 12h, 24h post-transfer."
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output:
  html_document:
    code_folding: hide
    theme: space
    toc: yes
    toc_depth: 3
    toc_float: no
  BiocStyle::html_document2:
    code_folding: hide
    toc: yes
    toc_float: yes
  knitrBootstrap::bootstrap_document:
    highlight.chooser: yes
    theme.chooser: yes
  pdf_document:
    toc: yes
always_allow_html: yes
---

```{r setup, bootstrap.show.code = FALSE, results='hide', bootstrap.show.message=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(bootstrap.show.code = FALSE, message=FALSE, warning=FALSE)
suppressMessages(library(magrittr))
suppressMessages(library(kableExtra))
suppressMessages(library(ggplot2))
suppressMessages(library(data.table))
suppressMessages(library(ggrepel))
suppressMessages(library(DESeq2))
suppressMessages(library(DiffBind))
```


# Samples

The following samples were part of this analysis:

```{r read_in_metadata, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, context="data"}
decoderFile <- "atac_decoder_diffBind.csv"
decoder.data <- read.table(decoderFile,header=T,stringsAsFactors=F, sep=",")
decoder.data$Condition = factor(decoder.data$Condition)
decoder.data$Condition <- relevel(decoder.data$Condition, ref = "N")
kable(decoder.data, row.names=FALSE,  padding = 0, longtable=TRUE) %>%  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

```{r read_in_counts, message=FALSE, warning=FALSE, cache=FALSE, echo=FALSE,  fig.width=10, fig.height=7, context="data"}
DB <- readRDS("DB.count.Rds")
DB <- dba.count(DB, peaks=NULL, score=DBA_SCORE_READS)
consensus_peaks <- dba.peakset(DB, peaks=NULL, bRetrieve=TRUE)
```

```{r createDDSobject, message=FALSE, warning=FALSE, cache=FALSE, echo=FALSE,  fig.width=10, fig.height=7, context="data"}
raw_counts = as.data.frame(mcols(consensus_peaks))
row.names(raw_counts) = paste0(as.data.frame(consensus_peaks)$seqnames, ":",as.data.frame(consensus_peaks)$start,"-",as.data.frame(consensus_peaks)$end)

#table(decoder.data$SampleID == colnames(raw_counts))

dds <- DESeqDataSetFromMatrix(countData = raw_counts,
                              colData = decoder.data,
                              design= ~ Condition)
dds <- DESeq(dds)
```

# PCA

Below is a PCA plot colored by condition using all the peaks in the peak atlas.

```{r pca, message=FALSE, warning=FALSE, cache=FALSE, echo=FALSE,  fig.width=6, fig.height=5, context="data", eval=T, fig.align="center"}
values <- log2(counts(dds, normalized=T)+1)

res <- list()
pc <- prcomp(t(values))

vr <- rep(0, length(pc$sdev))
for (i in 1:length(vr)) {
  vr[i] <- pc$sdev[i] ^ 2
}

comps = 1:3
c1 <- comps[1]
c2 <- comps[2]
c3 <- comps[3]
compnums <- c(c1, c2, c3)
pvar <- sum(vr[compnums[1:2]]) / sum(vr) * 100
c1p <- vr[c1] / sum(vr) * 100
c2p <- vr[c2] / sum(vr) * 100
c3p <- vr[c3] / sum(vr) * 100

plotData <- merge(pc$x[, c(c1, c2)], decoder.data, by.x="row.names", by.y="SampleID")

out.dt <- data.table(plotData, keep.rownames = TRUE)
out.dt[, x_center := median(PC1), by = "Condition"]
out.dt[, y_center := median(PC2), by = "Condition"]

ggplot(plotData, aes(PC1, PC2)) + geom_point(size = 6, aes(color = Condition), show.legend = T) + theme_bw(base_size =18)   + xlab( paste0("PC1: ", round(c1p, digits=2), "% variance")) + ylab( paste0("PC2: ", round(c2p, digits=2), "% variance")) + theme(legend.position="bottom")   + geom_point(shape = 1,size=6,colour = "black") + scale_color_manual(values=c("N" = "#636363", "E24" = "#66c2a4", "E12" = "#99d8c9", "E6" = "#ccece6", "L6" = "#c6dbef", "L12"  = "#6baed6"), name="")   + theme(plot.background = element_blank(), panel.grid.minor = element_blank(), panel.grid.major = element_blank()) + theme(legend.position ="none") + geom_label_repel(data=unique(out.dt[,c("x_center", "y_center", "Condition")]), aes(x = x_center, y = y_center, label = Condition), inherit.aes = FALSE, fontface = "plain", size = 6, segment.color = 'transparent') 
```

# Session Info
```{r session, message=FALSE, warning=FALSE, cache=FALSE,echo=FALSE, fig.width=10, fig.height=5.5, context="data"}
sessionInfo()
```

