---
title: Fig. 5b
subtitle: "Number of chromatin accessibility peak changes during CD8 T cell differentiation in tumors and infection across each transition."
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output:
  html_document:
    code_folding: hide
    theme: space
    toc: yes
    toc_depth: 3
    toc_float: no
  BiocStyle::html_document2:
    code_folding: hide
    toc: yes
    toc_float: yes
  knitrBootstrap::bootstrap_document:
    highlight.chooser: yes
    theme.chooser: yes
  pdf_document:
    toc: yes
always_allow_html: yes
---

```{r setup, bootstrap.show.code = FALSE, results='hide', bootstrap.show.message=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(bootstrap.show.code = FALSE, message=FALSE, warning=FALSE)
suppressMessages(library(magrittr))
suppressMessages(library(kableExtra))
suppressMessages(library(ggplot2))
suppressMessages(library(data.table))
suppressMessages(library(ggrepel))
suppressMessages(library(DESeq2))
suppressMessages(library(DiffBind))
suppressMessages(library(sva))
```


# Samples

The following samples were part of this analysis:

```{r read_in_metadata, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, context="data"}
decoderFile <- "atac_decoder_diffBind_plusPublic.csv"
decoder.data <- read.table(decoderFile,header=T,stringsAsFactors=F, sep=",")
decoder.data$Condition = factor(decoder.data$Condition)
decoder.data$Condition <- relevel(decoder.data$Condition, ref = "naive")
decoder.data$SampleID = make.names(decoder.data$SampleID)
kable(decoder.data, row.names=FALSE,  padding = 0, longtable=TRUE) %>%  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

```{r read_in_counts, message=FALSE, warning=FALSE, cache=FALSE, echo=FALSE,  fig.width=10, fig.height=7, context="data"}
DB <- readRDS("DB.count.plusPublic.Rds")
DB <- dba.count(DB, peaks=NULL, score=DBA_SCORE_READS)
consensus_peaks <- dba.peakset(DB, peaks=NULL, bRetrieve=TRUE)
```

```{r createDDSobject, message=FALSE, warning=FALSE, cache=FALSE, echo=FALSE,  fig.width=10, fig.height=7, context="data"}
raw_counts = as.data.frame(mcols(consensus_peaks))
row.names(raw_counts) = paste0(as.data.frame(consensus_peaks)$seqnames, ":",as.data.frame(consensus_peaks)$start,"-",as.data.frame(consensus_peaks)$end)

#table(decoder.data$SampleID == colnames(raw_counts))

dds <- DESeqDataSetFromMatrix(countData = raw_counts,
                              colData = decoder.data,
                              design= ~ Condition)
dds <- estimateSizeFactors(dds)

mod1 <- model.matrix(~Condition, decoder.data)
mod0 <- model.matrix(~1, decoder.data)

normCounts <-  counts(dds, normalized = TRUE)
svseq <- svaseq(normCounts, mod1, mod0, n.sv = 3)

decoder.data.sva <- cbind(decoder.data,data.frame(svseq$sv))
ddssva <- DESeqDataSetFromMatrix(countData = raw_counts,
                                 colData = decoder.data.sva,
                                 design= ~ X1 + X2 + X3 + Condition)
ddssva <- estimateSizeFactors(ddssva)

counts_sva = limma::removeBatchEffect(log2(normCounts+1), covariates = svseq$sv, design=mod1) # 

```


# Differential accessibility 

```{r runDESeq2, eval=F,echo=FALSE, message=FALSE, warning=FALSE,   context="data"}
ddssva <- DESeq(ddssva, parallel=F, fitType="parametric")
saveRDS(ddssva, "ddssva.RDS")
```

```{r da_res, eval=T,echo=FALSE, message=FALSE, warning=FALSE,   context="data"}
varInt="Condition"
dbs.all <- list()
alphaTR = 0.05

ddssva <- readRDS("ddssva.RDS")

comps = c("naive_vs_L6hr", "L6hr_vs_L12hr", "L12hr_vs_L5", "L5_vs_L7", "L7_vs_L14", "L14_vs_L21", "L21_vs_L28", "L28_vs_L35", "L35_vs_L60", "naive_vs_E6hr", "E6hr_vs_E12hr", "E12hr_vs_E24hr", "E24hr_vs_E5", "E5_vs_E7", "E7_vs_M")
for (comp in comps){
  levelRef <- strsplit(comp, "_vs_")[[1]][1]
  levelTest <- strsplit(comp, "_vs_")[[1]][2]
  cat(paste("Comparison", levelTest, "vs", levelRef, "done\n"))
  dbs.all[[paste0(levelTest,"_vs_",levelRef)]] <- 
    results(ddssva, contrast=c(varInt, levelTest, levelRef), alpha=alphaTR) %>% as.data.frame()
}


dbs.all.sig <- lapply(names(dbs.all), function(x){
  subset(dbs.all[[x]], padj < alphaTR)
   })
names(dbs.all.sig) <- names(dbs.all)
 
 
res = data.frame(sapply(dbs.all.sig, NROW))
colnames(res) <- paste0("padj<",alphaTR)

kable(res, row.names=T,  padding = 0, longtable=TRUE) %>%  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F)

```

# Barplots of changes

For below, changes between L14 and above were pooled (summed) into L14-T60, and E12-E24 were pooled.

```{r barplot_changes_fixed_summed, message=FALSE, warning=FALSE,  echo=FALSE,   fig.width=5, fig.height=5, context="data"}


names(dbs.all.sig) = gsub("naive", "N", names(dbs.all.sig))

da_changes = lapply(names(dbs.all.sig), function(x){
  name = paste0( strsplit(x, "_vs_")[[1]][2],"->",  strsplit(x, "_vs_")[[1]][1])
  df = dbs.all.sig[[x]] %>% dplyr::summarise(contrast = name, positive = sum(log2FoldChange>0), negative = sum(log2FoldChange<0))
  df
  }) %>% rbindlist() %>% melt()

colnames(da_changes) <- c("contrast", "sign", "value")
da_changes$type <- ifelse(grepl("L", da_changes$contrast), "lesion", "effector")


da_changes$contrast  = factor(da_changes$contrast, levels=c("N->L6hr", "L6hr->L12hr", "L12hr->L5", "L5->L7", "L7->L14", "L14->L21", "L21->L28", "L28->L35", "L35->L60","N->E6hr", "E6hr->E12hr", "E12hr->E24hr", "E24hr->E5", "E5->E7", "E7->M"))

lesions = subset(da_changes, type == "lesion")
lesions$contrast <- factor(lesions$contrast, levels=c("N->L6hr", "L6hr->L12hr", "L12hr->L5", "L5->L7", "L7->L14", "L14->L21", "L21->L28", "L28->L35", "L35->L60"))

l14_to_l60_pos = data.frame(contrast="L14->L60", 
           sign="positive", 
           value=sum(subset(lesions, contrast %in% c("L14->L21", "L21->L28", "L28->L35", "L35->L60") & sign == "positive")$value),
           type="lesion")

l14_to_l60_neg = data.frame(contrast="L14->L60", 
           sign="negative", 
           value=sum(subset(lesions, contrast %in% c("L14->L21", "L21->L28", "L28->L35", "L35->L60") & sign == "negative")$value),
           type="lesion")

lesions_sub = subset(lesions, !(contrast %in% c("L14->L21", "L21->L28", "L28->L35", "L35->L60")))

lesions_sub = rbind(lesions_sub, l14_to_l60_pos, l14_to_l60_neg)
lesions_sub$contrast <- factor(lesions_sub$contrast, levels=c("N->L6hr", "L6hr->L12hr", "L12hr->L5", "L5->L7", "L7->L14", "L14->L60"))

ggplot(data=lesions_sub, aes(x=contrast)) + 
geom_bar(data = subset(lesions_sub, sign == "positive"),  width=0.6666667,
   aes(y = value/1000, fill = sign), stat = "identity", position = "dodge") +
geom_bar(data = subset(lesions_sub, sign == "negative"),  width=0.6666667,
   aes(y = -value/1000, fill = sign), stat = "identity",  position = "dodge") + 
geom_hline(yintercept = 0,colour = "black") +theme_classic(base_size = 18) + xlab("") + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + ylab("# of peak changes (x 1k)")  + scale_fill_manual(labels=c("Closing", "Opening"), values=c("#0019f1", "#e53222")) + theme(legend.position="bottom") + theme(plot.background = element_blank(), panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.border=element_blank(), axis.line.x = element_blank()) +  theme(legend.title=element_blank(),   axis.ticks.x=element_blank()) + theme(legend.key.size = unit(0.4, 'cm')) + theme(legend.position = c(0.80, 0.85))  + ylim(c(-30,30))




effector = subset(da_changes, type == "effector")
effector$contrast <- factor(effector$contrast, levels=c("N->E6hr", "E6hr->E12hr", "E12hr->E24hr", "E24hr->E5", "E5->E7", "E7->M"))


e6_to_e24_pos = data.frame(contrast="E6hr->E24hr", 
           sign="positive", 
           value=sum(subset(effector, contrast %in% c("E6hr->E12hr", "E12hr->E24hr") & sign == "positive")$value),
           type="effector")

e6_to_e24_neg = data.frame(contrast="E6hr->E24hr", 
           sign="negative", 
           value=sum(subset(effector, contrast %in% c("E6hr->E12hr", "E12hr->E24hr") & sign == "negative")$value),
           type="effector")


blank_bar = data.frame(contrast=c("", ""), 
           sign=c("positive", "negative"), 
           value=c(0,0),
           type=c("effector", "effector"))

effector_sub = subset(effector, !(contrast %in% c("E6hr->E12hr", "E12hr->E24hr")))
effector_sub = rbind(effector_sub, e6_to_e24_pos, e6_to_e24_neg)
effector_sub$contrast <- factor(effector_sub$contrast, levels=c("N->E6hr", "E6hr->E24hr","E24hr->E5", "E5->E7", "E7->M"))


ggplot(data=effector_sub, aes(x=contrast)) + 
geom_bar(data = subset(effector_sub, sign == "positive"),  width=(0.6666667*(nrow(effector_sub)/2))/(nrow(lesions_sub)/2),
   aes(y = value/1000, fill = sign), stat = "identity", position = "dodge") +
geom_bar(data = subset(effector_sub, sign == "negative"),  width=(0.6666667*(nrow(effector_sub)/2))/(nrow(lesions_sub)/2),
   aes(y = -value/1000, fill = sign), stat = "identity",  position = "dodge") + 
geom_hline(yintercept = 0,colour = "black") +theme_classic(base_size = 18) + xlab("") + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + ylab("# of peak changes (x 1k)")  + scale_fill_manual(labels=c("Closing", "Opening"), values=c("#0019f1", "#e53222")) + theme(legend.position="bottom") + theme(plot.background = element_blank(), panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.border=element_blank(), axis.line.x = element_blank()) +  theme(legend.title=element_blank(),   axis.ticks.x=element_blank()) + theme(legend.key.size = unit(0.4, 'cm')) + theme(legend.position = c(0.80, 0.85))  + ylim(c(-30,30))
```


# Session Info
```{r session, message=FALSE, warning=FALSE, cache=FALSE,echo=FALSE, fig.width=10, fig.height=5.5, context="data"}
sessionInfo()
```

